language: ruby
os: osx
osx_image: xcode8.3
rvm: system

before_install:
  - export HOMEBREW_DEVELOPER=1
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - HOMEBREW_REPOSITORY="$(brew --repo)"
  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
  - git -C "$HOMEBREW_REPOSITORY" fetch;
  - git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master;
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"

script:
  - brew portable-package --write portable-ruby

notifications:
  email:
    on_success: never
    on_failure: always
