jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        export HOMEBREW_DEVELOPER=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew update-reset
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-portable-ruby"
        brew portable-package portable-ruby
      displayName: Tests

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        export HOMEBREW_DEVELOPER=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        export HOMEBREW_BUILD_FROM_SOURCE=1
        HOME="/home/linuxbrew"
        sudo mkdir "$HOME"
        sudo chown "$USER:" "$HOME"
        git clone --depth=1 https://github.com/Linuxbrew/brew "$HOME/.linuxbrew/Homebrew"
        mkdir "$HOME/.linuxbrew/bin"
        ln -s ../Homebrew/bin/brew "$HOME/.linuxbrew/bin/"
        PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
        ln -s "$PWD" "$HOME/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-portable-ruby"
        docker build -f docker/Dockerfile.x86_64 -t homebrew-portable-x86_64 .
        docker run homebrew-portable-x86_64 brew portable-package portable-ruby
      displayName: Tests
