jobs:
- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:
    - bash: |
        set -e
        sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
        export HOMEBREW_DEVELOPER=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew update-reset
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-portable-ruby"
        brew portable-package portable-ruby
      displayName: Tests

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        set -e
        docker build -f docker/Dockerfile.x86_64 -t homebrew-portable-x86_64 .
        # TODO: need to do something like:
        # docker cp "$PWD" $(docker container ls -lq):"$HOME/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-portable-ruby"
        # to actually test the correct Git version in this repo
        # docker run homebrew-portable-x86_64 brew portable-package portable-ruby
      displayName: Tests
