name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Check Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  tests:
    uses: ./.github/workflows/build.yml

  # This job is used as a required status check, instead of requiring each build matrix element.
  # When using ephemeral runners, the name of those runs change every time so they cannot be set as required.
  conclusion:
    needs: tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Result
        run: ${{ needs.tests.result == 'success' }}
